TITLE "MAIN"
LIST P=16F1826
#INCLUDE "P16F1826.INC"

__CONFIG _CONFIG1,(_FOSC_INTOSC & _WDTE_OFF & _PWRTE_OFF &_MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _CLKOUTEN_OFF & _IESO_OFF & _FCMEN_OFF)

ORG 0X0000
	GOTO	START

ORG	0X0004
	GOTO	ISR

ORG 0X0010
	START	
	CLRF	STATUS
	CLRF	LATA
	CLRF	LATB

	BANKSEL	TRISB
	MOVLW	B'11011111'
	MOVWF	TRISB
	MOVLW	B'00111100'
	MOVWF	TRISA
	MOVLW	0xF0
	MOVWF	OSCCON

	BANKSEL	ANSELB
	MOVLW	0X00
	MOVWF	ANSELB
	MOVLW	0X10
	MOVWF	ANSELA

	BANKSEL	PIR1
	BCF		PIR1,6 		;clear adc interrupt flag

	BANKSEL PIE1
	BSF		PIE1,6		;enable adc interrupt
	MOVLW	B'11001000'	;also enable interrupt on change
	MOVWF	INTCON		;enable global and peripheral interrupt
	BANKSEL	IOCBP
	MOVLW	B'11111111'
	MOVWF	IOCBP
	MOVWF	IOCBN 

	BANKSEL	ADCON1	
	MOVLW	B'01110000'
	MOVWF	ADCON1		;right justified adc reading
	MOVLW	B'00010011'
	MOVWF	ADCON0		;pick out the channel for ADC and turn on

LOOP
	GOTO	LOOP

ISR
	BANKSEL ADCON0	
	BTFSS	ADCON0,ADGO
	GOTO	ADC_ISR
	GOTO	QUAD_ISR

ADC_ISR
	BANKSEL	ADRESH
	MOVF	ADRESH,W 	;copy over voltage reading to WREG

	BANKSEL	PORTA
	BTFSS	WREG,7		;check if greater than "6" on VRT TORQUE
	BCF 	PORTA,7
	BTFSC	WREG,7
	BSF 	PORTA,7	
	BSF		ADCON0,ADGO	;start the adc again
	BSF 	INTCON,7	;re-enable the global interrupt

	BANKSEL	PIR1
	BCF		PIR1,6 		;clear adc interrupt flag
	RETFIE	

QUAD_ISR
	BANKSEL	PORTA

	BTFSC	PORTB,3
	CALL	CHECK_RB2

	BTFSC	PORTB,2
	CALL	CHECK_RB3

	BTFSC	PORTB,1
	CALL	CHECK_RB4

	BTFSC	PORTB,4
	CALL	CHECK_RB1

	RETFIE

CHECK_RB2
	BTFSC	PORTB,2
	BCF		PORTA,0
	BTFSS	PORTB,2
	BSF		PORTA,0
	CALL	RESET_IOC
	RETURN

CHECK_RB3
	BTFSC	PORTB,3
	BCF		PORTA,0
	BTFSS	PORTB,3
	BSF		PORTA,0
	CALL 	RESET_IOC
	RETURN

CHECK_RB4
	BTFSC	PORTB,4
	BCF		PORTA,1
	BTFSS	PORTB,4
	BSF		PORTA,1
	CALL 	RESET_IOC
	RETURN

CHECK_RB1
	BTFSC	PORTB,1
	BCF		PORTA,1
	BTFSS	PORTB,1
	BSF		PORTA,1
	CALL 	RESET_IOC	
	RETURN

RESET_IOC
	MOVLW 	0xff
	XORWF 	IOCBF, W
	ANDWF 	IOCBF, F
	RETURN

END